version: 0.0.{build}
image: Visual Studio 2017

branches:
   only:
     - master

install:
  - cmd: git submodule update --init --recursive
  - cmd: mkdir Build
  - cmd: cd Build
  - cmd: cmake -G "Visual Studio 15 2017 -DINSTALL_GTEST=0" ..