version: 0.0.{build}
image: Visual Studio 2019

branches:
   only:
     - master

environment:
  matrix:
    - GENERATOR: "Visual Studio 16"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 16"
      CONFIG: Release

    - GENERATOR: "Visual Studio 16 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 16 Win64"
      CONFIG: Release

build_script:
  - cmd: git submodule update --init --recursive
  - cmd: cmake -G "%GENERATOR%" -BBuild -DINSTALL_GTEST=0 -DBUILD_GMOCK=0 .
  - cmd: cmake --build Build --config "%CONFIG%"

test_script:
  - ctest -VV -C "%CONFIG%"